### ISSUE TITLE
Relation field not storing relationships consistently

### ISSUE THREAD

**Issue by tawanorg** [CannerCMS/cannercms#153] opened 2019-02-23 06:39 UTC
Last item set is `NULL` as always. 

```
<array
        keyName="layers" 
        title="Layers" 
        ui="panel"
        refetch
        graphql={`
          query($pagesWhere: PageWhereInput) {
            pages: pagesConnection(where: $pagesWhere) {
              edges {
                cursor
                node {
                  id
                  title
                }
              }
            }
          }
        `}
      >
        <relation
          title="Child Layers"
          keyName="childLayers"
          ui="singleSelectTree"
          relation={{to: 'layers', type: 'toOne'}}
          uiParams={{
            relationField: 'childLayers',
            textCol: 'title',
            columns: [
              {
                title: "${layers.title}",
                dataIndex: "title"
              }
            ],
            relationField: "layers"
          }}
        />
      </array>
```
![screen shot 2562-02-18 at 19 16 35](https://user-images.githubusercontent.com/10970130/53282863-00390300-3792-11e9-8475-60c474c5e1e4.png)

**Comment by wwwy3y3** [comment] 2019-02-23 06:52
Hi @ttawan 

May I know the following information
* OS
* Node version
* Canner version

Thanks

**Comment by wwwy3y3** [comment] 2019-02-23 07:05
@ttawan Please provide us your full canner schema as well, so we can reproduce your situation.

Thanks

**Comment by wwwy3y3** [comment] 2019-02-26 02:10
hi @ttawan any update on this issue?

After taking a look at your data, I believe you use a relation field inside an array field, which is not an acceptable schema currently. Hope it helps.

Thanks!

**Comment by wwwy3y3** [comment] 2019-02-27 03:36
temporarily close this issue due to no further response from the issuer.

**Closed as completed by wwwy3y3** 2019-02-27 03:36 UTC
